sources:
  bundler: true

allowed:
  - mit
  - apache-2.0

reviewed:
  bundler:
    # ruby license
    - json
    - pathname-common_prefix

    # bsd-2 or ruby
    - logger
    - net-http
    - racc
    - uri

    # dwtfyw
    - reverse_markdown
